### ISSUE TITLE
Owner Ship Rights

### ISSUE THREAD

**Issue by yodatom10** [ECE-Engineer/PriorityEmailNotifier#2]
If your are not going to continue to actively develop this project please transfer the rights over. I have future plans for PEN but to do it most effectively I need to be able to tweak the repo setup.

**Comment by ECE-Engineer** [comment]
If I am correct, you both had already created a repo with all the same stuff as the PEN repo. Am I wrong?

**Comment by AakankshaRaika** [comment]
Please do not be rude ok ! if we were cheats we would have never added you
as a contributed in the new repo. You are not working on it and we dont
want 2 of same projects I am sure we all as adults can reach an mutual
ground.

On Tue, Mar 22, 2016 at 2:51 PM, <>(CK)<> notifications@github.com wrote:

> If I am correct, you both had already created a repo with all the same
> stuff as the PEN repo. Am I wrong?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ECE-Engineer/PriorityEmailNotifier/issues/2#issuecomment-199960091

## 

Best Regards
Aakanksha Raika

**Comment by ECE-Engineer** [comment]
LOL. I pretty sure I'm not being rude. By the way, I learned that you could've forked the repo at the same time you both pestering me about this. 

Also you never really gave me time to tell you both that, I never really go on facebook that much so by the time I did go on you both were beyond the point of asking me for the ownership rights, please realize this next time. Just be more patient.

**Comment by AakankshaRaika** [comment]
Ok agreed we could have been more patient. But please understand that was my first Idea you have done so make projects? Werent you ever protective about the first one you worked on ? and Thought about?

**Comment by AakankshaRaika** [comment]
Forking is not same as owning the idea Kyle. you do not want to see that fine dont but you arent even working on it... we both are..

**Comment by AakankshaRaika** [comment]
But keeping the right when you arnt even working on it.. and making us ask you for it again and again and not willing to work on a common ground where everyone is happy isnt mature of you either

**Comment by AakankshaRaika** [comment]
Hi ECE-Engineer/Priorit,

I'd like to add you to my professional network on LinkedIn.

- Aakanksha

Confirm that you know Aakanksha: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=HjGYU9sT&invitationId=6195086895681191936&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiuj9vekd%7Ebt








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iuj9vekd-bt&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH6XHasWeRf3QAAAVfle6TrLe7VNaS5Kx3UDxwdN95xsHuV88qoQHrbmL0bCn1A4g_H-ftyLdgeYYAZJ5k4VDVs2T3XW9PAjrlawTHu_u-_sN8gVayeeyzEMsEXgGQ5wCrxtQ3QEaIaPxVpcl1DBgpMOlqzagDUs819YJ-ypeWXtQF1oHVOnM66_ZtlaUp8BYT8&eid=0-iuj9vekd-bt


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iuj9vekd-bt&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
